name: Action-Test

on: [push]

jobs:
  Check GDML:
    runs-on: ubuntu-latest
    name: Check GDML file
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/check-gdml-action@v0
      with:
        gdml-file: "test.gdml"
