name: Action-Test

on: [push]

jobs:
  Check-GDML:
    runs-on: ubuntu-latest
    name: Check-GDML-file
    steps:
    - name: GDML-Check
      id: hello
      uses: actions/gdml-check-action@v0
      with:
        gdml-file: "test.gdml"
